SELECT * FROM TB_PRODUTOS;

DELETE FROM TB_PRODUTOS WHERE PRODUTO = '1037797';

-----------------------------------------------------

SELECT * FROM TB_VENDEDORES;

DELETE FROM TB_VENDEDORES WHERE MATRICULA = '00400';