SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_PRODUTOS
    (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
    ('1037797', 'Clean - 2 Litros - Laranja',
     'PET', '2 Litros', 'Laranja', 16.01);
     
DELETE FROM TB_PRODUTOS WHERE PRODUTO = '1037797';   

ALTER TABLE TB_PRODUTOS ADD CONSTRAINT
            PK_TB_PRODUTOS PRIMARY KEY (PRODUTO);

----------------------------------------------------------------
DELETE FROM TB_VENDEDORES WHERE MATRICULA = '00414';
SELECT * FROM TB_VENDEDORES;

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT
            PK_TB_VENDEDDORES PRIMARY KEY (MATRICULA);
            
