/* --------------------------------- Aula 6 ------------------------------------
                                     Vendas                                   */
                                     
--------------------------------------------------------------------------------

-- Aula 6.1 - Vendas válidas

SELECT * FROM TABELA_DE_CLIENTES;

-- Valor total de vendas por mês de cada cliente
SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS "Mês/Ano", 
       SUM(INF.QUANTIDADE) AS "Quantidade Total"
    FROM NOTAS_FISCAIS NF   
INNER JOIN ITENS_NOTAS_FISCAIS INF ON (NF.NUMERO = INF.NUMERO)
GROUP BY CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY');  


SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;


SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO,  TV.QUANTIDADE_TOTAL
    FROM TABELA_DE_CLIENTES TC
INNER JOIN 
    (SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
        FROM NOTAS_FISCAIS NF   
INNER JOIN ITENS_NOTAS_FISCAIS INF ON (NF.NUMERO = INF.NUMERO)
GROUP BY CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') ) TV
    ON TV.CPF = TC.CPF;
    
    
SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO,  TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'Vendas Válidas'
ELSE 'Vendas Inválidas' END) AS "Resultado"
    FROM TABELA_DE_CLIENTES TC
INNER JOIN 
    (SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
        FROM NOTAS_FISCAIS NF   
INNER JOIN ITENS_NOTAS_FISCAIS INF ON (NF.NUMERO = INF.NUMERO)
GROUP BY 
CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') ) TV
ON (TV.CPF = TC.CPF)
WHERE TV.MES_ANO = '02-2015';    
    
    
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100,2)
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
NF.CPF,
TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
CPF, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')) TV
ON TV.CPF = TC.CPF
WHERE TV.MES_ANO = '02-2015'
AND (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0;

--------------------------------------------------------------------------------

-- Aula 6.2 - Vendas por sabor

SELECT TP.SABOR,
       EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF ON (TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO)
INNER JOIN NOTAS_FISCAIS NF ON (INF.NUMERO = NF.NUMERO)
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR,
         EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;


SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
(SELECT EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
    FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON (NF.NUMERO = INF.NUMERO)
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO


SELECT TP.SABOR,
       EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
    ( 
       SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
(SELECT EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
    FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON (NF.NUMERO = INF.NUMERO)
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO
        ) AS QUANTIDADE_GERAL       
    FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF ON (TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO)
INNER JOIN NOTAS_FISCAIS NF ON (INF.NUMERO = NF.NUMERO)
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR,
         EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;


SELECT CONSULTA_RELATORIO.SABOR, CONSULTA_RELATORIO.ANO, CONSULTA_RELATORIO.QUANTIDADE_TOTAL,
ROUND((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.QUANTIDADE_GERAL) *100, 2) 
AS PERCENTUAL_PARTICIPACAO
    FROM
(SELECT
TP.SABOR,
EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
(SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
    (SELECT
     EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
     SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
    FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
    WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
    GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO) AS QUANTIDADE_GERAL
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO
    WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
    GROUP BY TP.SABOR,EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) CONSULTA_RELATORIO;

-----------------------------------------------------------------------------------

-- Agora para ver o ranking das vendas por tamanho.
SELECT CONSULTA_RELATORIO.TAMANHO, 
CONSULTA_RELATORIO.ANO,
CONSULTA_RELATORIO.QUANTIDADE_TOTAL,
ROUND((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.QUANTIDADE_GERAL) * 100, 2)
AS PERCENTUAL_PARTICIPACAO
FROM
(SELECT
TP.TAMANHO,EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO ,SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
,(SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
(SELECT
EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
,SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO
) AS QUANTIDADE_GERAL
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO,EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) CONSULTA_RELATORIO;
