-- Aula 2.1 - Criando as tabelas via comandos SQL

CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS INTEGER NULL,
PRIMARY KEY (MATRICULA));

ALTER TABLE VENDEDORES
RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;

CREATE TABLE TAB_EMPRESA
(cod_empresa VARCHAR(5) PRIMARY KEY,
nome_empresa VARCHAR(50));

CREATE TABLE TAB_DEPARTAMENTO
(cod_departamento VARCHAR(5) PRIMARY KEY,
nome_departamento VARCHAR(50),
cidade_departamento VARCHAR(50),
cod_empresa VARCHAR(5));

CREATE TABLE TAB_PROJETO
(cod_projeto VARCHAR(5) PRIMARY KEY,
nome_projeto VARCHAR(50),
orcamento_projeto FLOAT,
data_inicio_projeto DATE,
cod_departamento VARCHAR(5));

--------------------------------------------------------------------------------

-- Aula 2.2 Criando as tabelas com chave estrangeira

CREATE TABLE TAB_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NOT NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY(NUMERO));

ALTER TABLE TAB_VENDAS 
ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF);

ALTER TABLE TAB_VENDAS 
ADD CONSTRAINT FK_VENDEDORES FOREIGN KEY(MATRICULA) REFERENCES VENDEDORES(MATRICULA);

ALTER TABLE TAB_DEPARTAMENTO
ADD CONSTRAINT FK_TAB_EMPRESA FOREIGN KEY (COD_EMPRESA)
REFERENCES TAB_EMPRESA(COD_EMPRESA);

ALTER TABLE TAB_PROJETO
ADD CONSTRAINT FK_TAB_DEPARTAMENTO FOREIGN KEY (COD_DEPARTAMENTO)
REFERENCES TAB_DEPARTAMENTO(COD_DEPARTAMENTO);

ALTER TABLE TAB_FUNCIONARIO
ADD CONSTRAINT FK_TAB_DEPARTAMENTO_FUNC FOREIGN KEY (COD_DEPARTAMENTO)
REFERENCES TAB_DEPARTAMENTO(COD_DEPARTAMENTO);

ALTER TABLE TAB_DEPENDENTE
ADD CONSTRAINT FK_TAB_DEPARTAMENTO_DEPENDENTE FOREIGN KEY (COD_FUNCIONARIO)
REFERENCES TAB_FUNCIONARIO(COD_FUNCIONARIO);

--------------------------------------------------------------------------------

-- Aula 2.3 - Renomeando tabelas e colunas

ALTER TABLE TAB_VENDAS RENAME to NOTAS;

ALTER TABLE "SYSTEM"."TAB_DEPARTAMENTO" RENAME COLUMN "CIDADE_DEPARTAMENTO" to "cidade";

alter table "SYSTEM"."TAB_PROJETO" rename column "ORCAMENTO_PROJETO" to "orcamento";

alter table "SYSTEM"."TAB_PROJETO" rename column "data_inicio_projeto" to "data_inicio"

alter table "SYSTEM"."TAB_DEPENDENTE" rename column "TIPO_DEPENDENTE" to "TIPO";

alter table "SYSTEM"."TAB_DEPENDENTE" rename column "IDADE_DEPENDENTE" to "IDADE";

--------------------------------------------------------------------------------

-- Aula 2.4 - Finalizando a criação dos campos

CREATE TABLE ITENS_NOTAS
(NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE INTEGER NULL,
PRECO FLOAT,
PRIMARY KEY (NUMERO, CODIGO));

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_NOTAS 
FOREIGN KEY (NUMERO) REFERENCES NOTAS(NUMERO);

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_PRODUTOS 
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS(CODIGO);



