-- Aula 5.1 - Apagando linhas sincronizando com outra tabela

SELECT * FROM TABELA_DE_PRODUTOS_FONTE;

DELETE FROM TABELA_DE_PRODUTOS_FONTE WHERE CODIGO_DO_PRODUTO = '9999999';

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001001','Sabor dos Alpes 700 ml - Manga','Manga','700 ml','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001000','Sabor dos Alpes 700 ml - Melão','Melão','700 ml','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001002','Sabor dos Alpes 700 ml - Graviola','Graviola','700 ml','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001003','Sabor dos Alpes 700 ml - Tangerina','Tangerina','700 ml','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001004','Sabor dos Alpes 700 ml - Abacate','Abacate','700 ml','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001005','Sabor dos Alpes 700 ml - Açai','Açai','700 ml','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001006','Sabor dos Alpes 1 Litro - Manga','Manga','1 Litro','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001007','Sabor dos Alpes 1 Litro - Melão','Melão','1 Litro','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001008','Sabor dos Alpes 1 Litro - Graviola','Graviola','1 Litro','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001009','Sabor dos Alpes 1 Litro - Tangerina','Tangerina','1 Litro','Garrafa',7.50);

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES ('1001010','Sabor dos Alpes 1 Litro - Abacate','Abacate','1 Litro','Garrafa',7.50);

SELECT * from PRODUTOS WHERE SUBSTR(DESCRITOR,1,15) = 'Sabor dos Alpes';

SELECT * from TABELA_DE_PRODUTOS_FONTE WHERE SUBSTR(NOME_DO_PRODUTO,1,15) = 'Sabor dos Alpes';

DELETE FROM PRODUTOS WHERE CODIGO = '1001000';

SELECT COUNT(*) FROM PRODUTOS;
SELECT COUNT(*) FROM TABELA_DE_PRODUTOS_FONTE;

SELECT P.CODIGO AS CODIGO_PRODUTOS, TPF.CODIGO_DO_PRODUTO AS CODIGO_FONTE,
       P.DESCRITOR AS DESCRITOR_PRODUTOS, TPF.NOME_DO_PRODUTO AS DESCRITOR_FONTE
    FROM PRODUTOS P
LEFT JOIN TABELA_DE_PRODUTOS_FONTE TPF
    ON P.CODIGO = TPF.CODIGO_DO_PRODUTO;
 
SELECT P.CODIGO
    FROM PRODUTOS P
LEFT JOIN TABELA_DE_PRODUTOS_FONTE TPF ON P.CODIGO = TPF.CODIGO_DO_PRODUTO
    WHERE TPF.CODIGO_DO_PRODUTO IS NULL;
   
DELETE FROM PRODUTOS P 
WHERE P.CODIGO IN
(SELECT P.CODIGO
    FROM PRODUTOS P
LEFT JOIN TABELA_DE_PRODUTOS_FONTE TPF ON P.CODIGO = TPF.CODIGO_DO_PRODUTO
    WHERE TPF.CODIGO_DO_PRODUTO IS NULL);
    
CREATE TABLE TAB_RH_DEMITIDOS (COD_FUNCIONARIO VARCHAR(5));

INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0001');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0005');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0012');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0022');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0033');

DELETE FROM TAB_DEPENDENTE TD 
    WHERE TD.COD_FUNCIONARIO IN 
    (SELECT TD.COD_FUNCIONARIO 
        FROM TAB_DEPENDENTE TD 
    INNER JOIN TAB_RH_DEMITIDOS TRD ON TD.COD_FUNCIONARIO = TRD.COD_FUNCIONARIO);

DELETE FROM TAB_FUNCIONARIO TF 
WHERE TF.COD_FUNCIONARIO IN 
    (SELECT TF.COD_FUNCIONARIO
        FROM TAB_FUNCIONARIO TF 
        INNER JOIN TAB_RH_DEMITIDOS TRD ON TF.COD_FUNCIONARIO = TRD.COD_FUNCIONARIO);
        
--------------------------------------------------------------------------------

-- Aula 5.2 - Entendendo uma transação

SELECT COUNT(*) FROM PRODUTOS;

COMMIT;

-- Aula 5.3 - Commit e Rollback

CREATE TABLE PRODUTOS2 AS (SELECT * FROM PRODUTOS);

SELECT * FROM PRODUTOS2;

UPDATE PRODUTOS2 SET PRECO_LISTA = 8;
COMMIT;

UPDATE PRODUTOS2 SET PRECO_LISTA = 7;
ROLLBACK;

CREATE TABLE TAB_TRANSACAO (CAMPO INTEGER);
INSERT INTO TAB_TRANSACAO VALUES (1);
INSERT INTO TAB_TRANSACAO VALUES (2);
INSERT INTO TAB_TRANSACAO VALUES (3);
COMMIT;
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 1;
INSERT INTO TAB_TRANSACAO VALUES (4);
ROLLBACK;
INSERT INTO TAB_TRANSACAO VALUES (1);
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 2;
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 3;
COMMIT;
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 1;
INSERT INTO TAB_TRANSACAO VALUES (1);
INSERT INTO TAB_TRANSACAO VALUES (2);
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 4;
COMMIT;
INSERT INTO TAB_TRANSACAO VALUES (3);
INSERT INTO TAB_TRANSACAO VALUES (4);
ROLLBACK;

SELECT * FROM TAB_TRANSACAO;