-- Aula 4.1 - Alterando dados da tabela

SELECT * FROM PRODUTOS WHERE CODIGO = '1040107';

UPDATE PRODUTOS SET PRECO_LISTA = 5.2 WHERE CODIGO = '1040107';

SELECT * FROM PRODUTOS;

UPDATE PRODUTOS SET SABOR = 'Laranja', EMBALAGEM = 'PET' WHERE CODIGO = '1040107';

-- Replace altera um pedaço de um texto subs por outro texto

SELECT DESCRITOR, REPLACE (DESCRITOR, 'Melancia', 'Laranja') FROM PRODUTOS WHERE CODIGO = '1040107';

UPDATE PRODUTOS SET DESCRITOR = REPLACE (DESCRITOR, 'Melancia', 'Laranja') WHERE CODIGO = '1040107';

SELECT * FROM PRODUTOS WHERE SABOR = 'Maracuja';

UPDATE PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 1.10 WHERE SABOR = 'Maracuja';

--  acrescentar 1 ano à idade de todos os dependentes.
UPDATE TAB_DEPENDENTE SET IDADE = IDADE + 1;

--------------------------------------------------------------------------------

-- Aula 4.2 - Inner Join no update

  CREATE TABLE "TABELA_DE_VENDEDORES_FONTE" 
   ("MATRICULA" NVARCHAR2(5), 
    "NOME" NVARCHAR2(100), 
    "PERCENTUAL_COMISSAO" FLOAT(126), 
    "DATA_ADMISSAO" DATE, 
    "DE_FERIAS" NUMBER(1,0), 
    "BAIRRO" NVARCHAR2(50)
   );

Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00235','Marcio Almeida Silva','0,08',to_date('15/08/14','DD/MM/RR'),'0','Tijuca');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00236','Claudia Morais','0,08',to_date('17/09/13','DD/MM/RR'),'1','Jardins');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00237','Roberta Martins','0,11',to_date('18/03/17','DD/MM/RR'),'1','Copacabana');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00238','Pericles Alves','0,11',to_date('21/08/16','DD/MM/RR'),'0','Santo Amaro');

SELECT * FROM VENDEDORES V;
SELECT * FROM TABELA_DE_VENDEDORES_FONTE TVF;

SELECT V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
    FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF 
    ON (V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));
    
UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 0 WHERE MATRICULA IN ('00236', '00237');
UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 1 WHERE MATRICULA IN ('00235', '00238');

UPDATE VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF ON (V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));
SET V.FERIAS = TVF.FERIAS;

--------------------------------------------------------------------------------

-- Aula 4.3 - Entendendo o comando EXISTS


SELECT V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
    FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF 
    ON (V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));
    
-- EXISTS

SELECT V.MATRICULA AS MATRICULA_VENDEDORES,
       V.FERIAS AS FERIAS_VENDEDORES
    FROM VENDEDORES V
WHERE EXISTS
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
 WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));
 
INSERT INTO TABELA_DE_VENDEDORES_FONTE
    VALUES('00239', 'José Maria', 0.12, TO_DATE('2018-01-01', 'YYYY-MM-DD'), 1, 'Tijuca');

SELECT V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
    FROM VENDEDORES V
RIGHT JOIN TABELA_DE_VENDEDORES_FONTE TVF 
    ON (V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));
    
SELECT V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
    FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF 
    ON (V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));

/* qual comando que lista o nome dos funcionários que possuem dependentes,
usando apenas o comando EXISTS?

SELECT DISTINCT TF.NOME_FUNCIONARIO
FROM TAB_FUNCIONARIO TF
WHERE EXISTS
(SELECT 1 FROM TAB_DEPENDENTE TD
WHERE TF.COD_FUNCIONARIO = TD.COD_FUNCIONARIO);  */

--------------------------------------------------------------------------------

-- Aula 4.4 - Aplicando o EXISTS no UPDATE

SELECT V.MATRICULA AS MATRICULA_VENDEDORES,
       V.FERIAS AS FERIAS_VENDEDORES
    FROM VENDEDORES V
WHERE EXISTS
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
 WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));
 
SELECT V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
    FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF 
    ON (V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3)); 
 
UPDATE VENDEDORES V SET V.FERIAS = 
(SELECT TVF.DE_FERIAS FROM TABELA_DE_VENDEDORES_FONTE TVF
WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3))
WHERE EXISTS
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
 WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3));;
 
UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 1 
WHERE MATRICULA IN ('00236', '00237');

--------------------------------------------------------------------------------
CREATE TABLE TAB_PROJETO_ORCAMENTO
(cod_projeto VARCHAR(5), percentual_novo_orcamento FLOAT);

INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0001',0.2);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0002',0.1);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0003',-0.1);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0005',0.23);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0007',0.09);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0008',-0.03);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0009',-0.05);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0011',0.123);

UPDATE TAB_PROJETO P 
SET P.orcamento = P.orcamento * ( 1 + 
(SELECT TBO.percentual_novo_orcamento FROM TAB_PROJETO_ORCAMENTO TBO
WHERE P.COD_PROJETO = TBO.COD_PROJETO))
WHERE EXISTS
(SELECT 1 FROM TAB_PROJETO_ORCAMENTO TBO
WHERE P.COD_PROJETO = TBO.COD_PROJETO);
--------------------------------------------------------------------------------